sudo: required
language: node_js

node_js:
  - "0.10"

services:
  - mongodb

cache:
  directories:
    - ~/.meteor

before_install:
  - "curl https://install.meteor.com | /bin/sh"

#script: ./run_nightwatch.sh